version: "3.8"
services:
    nodeserver:
        build:
            context: ./reverse-proxy
        ports:
            - "3333:3333"
    nginx:
        restart: always
        build:
            context: ./nginxfolder
        ports:
            - "8080:80"
        links:
           - nodeserver:server
        depends_on:
           - nodeserver
